version: "3.8"
services:
   k-means-spark:
       build: .
       command: bash -c "python src/main.py"
       image: danielto1404/k-means-spark-datamart:latest
       ports:
           - "4040:4040"
           - "8888:8888"
       depends_on:
           clickhouse:
               condition: service_healthy

   clickhouse:
       container_name: clickhouse
       image: yandex/clickhouse-server
       platform: linux/amd64
       ports:
           - "9000:9000"
           - "8123:8123"
       volumes:
           - ./data/en.openfoodfacts.org.products.csv:/var/lib/clickhouse/user_files/en.openfoodfacts.org.products.csv
           - ./scripts/init_clickhouse.sh:/docker-entrypoint-initdb.d/init_clickhouse.sh
       healthcheck:
           test: [ "CMD", "wget", "--spider", "-q", "localhost:8123/ping" ]
           interval: 30s
           timeout: 5s
           retries: 3
       privileged: true